services:
  postgres_airflow:
    image: postgres:15
    container_name: postgres_airflow
    environment:
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: weather_pass
      POSTGRES_DB: weather_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata_airflow:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.9.1
    container_name: airflow-webserver
    restart: always
    depends_on:
      - airflow-scheduler
      - postgres_airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://weather_user:weather_pass@postgres_airflow:5432/weather_db
      AIRFLOW__CORE__FERNET_KEY: 'HBLr2mIktbrlKZ2My6P2gFPXqJt5BBaEy6Ei0kM0gI0='
      AIRFLOW__WEBSERVER__SECRET_KEY: 'M10SxQOy0UXUrMxuNM_vqVvMzDW-GD2suuw4a2QE1wY'
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'true'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./.env:/opt/airflow/.env
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.9.1
    container_name: airflow-scheduler
    depends_on:
      - postgres_airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://weather_user:weather_pass@postgres_airflow:5432/weather_db
      AIRFLOW__CORE__FERNET_KEY: 'HBLr2mIktbrlKZ2My6P2gFPXqJt5BBaEy6Ei0kM0gI0='
      AIRFLOW__WEBSERVER__SECRET_KEY: 'M10SxQOy0UXUrMxuNM_vqVvMzDW-GD2suuw4a2QE1wY'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./.env:/opt/airflow/.env
    command: scheduler

volumes:
  pgdata_airflow:
